# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-09 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=1000)),
                ('attachment', models.FileField(upload_to='documents')),
                ('language', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('AdibsLanguage', 'AdibsLanguage')], max_length=100, null=True)),
                ('framework', models.CharField(choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Spring boot', 'Spring boot')], max_length=100, null=True)),
                ('database', models.CharField(choices=[('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB')], max_length=100, null=True)),
                ('technology', models.CharField(choices=[('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB')], max_length=100, null=True)),
            ],
        ),
    ]
