# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='technology',
            field=models.CharField(choices=[('AWS', 'AWS'), ('Programming', 'Programming'), ('Git', 'Git'), ('Web', 'Web'), ('Machine Learning', 'Machine Learning')], max_length=100, null=True),
        ),
    ]
