# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource', '0003_auto_20190910_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
