# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource', '0006_auto_20190910_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='created_date',
        ),
    ]
