# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-10 12:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource', '0010_remove_resource_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 10, 12, 48, 7, 548924, tzinfo=utc), null=True),
        ),
    ]
