# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource', '0012_auto_20190910_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='database',
            field=models.CharField(blank=True, choices=[('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='framework',
            field=models.CharField(blank=True, choices=[('Django', 'Django'), ('Flask', 'Flask'), ('Spring boot', 'Spring boot')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='language',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('Ruby', 'Ruby'), ('AdibsLanguage', 'AdibsLanguage')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='technology',
            field=models.CharField(blank=True, choices=[('AWS', 'AWS'), ('Programming', 'Programming'), ('Git', 'Git'), ('Web', 'Web'), ('Machine Learning', 'Machine Learning')], max_length=100, null=True),
        ),
    ]
