# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource', '0014_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
