# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-17 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resource_test', '0002_database_framework_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents')),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('framework', models.CharField(blank=True, max_length=100, null=True)),
                ('database', models.CharField(blank=True, max_length=100, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
